#ifndef SOH_MOD_API_PLAYER_HOOK_TYPES_H
#define SOH_MOD_API_PLAYER_HOOK_TYPES_H

typedef enum {
    SOH_PLAYER_ACTION_FIRST_PERSON,
    SOH_PLAYER_ACTION_DOOR,
    SOH_PLAYER_ACTION_RECEIVE_ITEM,
    SOH_PLAYER_ACTION_MOUNT_HORSE,
    SOH_PLAYER_ACTION_TALK,
    SOH_PLAYER_ACTION_WALL,
    SOH_PLAYER_ACTION_ROLL,
    SOH_PLAYER_ACTION_MELEE,
    SOH_PLAYER_ACTION_SPIN_CHARGE,
    SOH_PLAYER_ACTION_THROW,
    SOH_PLAYER_ACTION_ZTARGET_A,
    SOH_PLAYER_ACTION_SHIELD,
    SOH_PLAYER_ACTION_LEDGE,
    SOH_PLAYER_ACTION_ITEM_ON_ACTOR,
    SOH_PLAYER_ACTION_MAX,
} SOHPlayerAction;

typedef enum {
    SOH_PLAYER_MOTION_STICK_SPEED,
    SOH_PLAYER_MOTION_SPEED_CAP,
} SOHPlayerMotionKind;

typedef enum {
    SOH_PLAYER_ANIM_SITE_HOP,
    SOH_PLAYER_ANIM_SITE_DAMAGE,
    SOH_PLAYER_ANIM_SITE_FIDGET,
    SOH_PLAYER_ANIM_SITE_FALL,
} SOHPlayerAnimSite;

typedef enum {
    SOH_ACTOR_SFX_VOICE,
    SOH_ACTOR_SFX_STEP,
    SOH_ACTOR_SFX_JUMP,
    SOH_ACTOR_SFX_LAND,
    SOH_ACTOR_SFX_GENERIC,
    SOH_ACTOR_SFX_FLAGGED,
} SOHActorSfxKind;

#endif
