#ifndef SSBB_SKIN_H
#define SSBB_SKIN_H

#include "z64.h"
#include "expansions/ssbb/ssbb_character.h"

#define SSBB_MAX_INFLUENCES 4  // max bones per vertex (COLLADA standard)
#define SSBB_MAX_SKIN_BONES 64 // max bones in a skinned character

// Per-vertex bind-pose data (generated by converter, static)
typedef struct {
    f32 posX, posY, posZ;   // rest position in DAE space (float for precision)
    s8 normX, normY, normZ; // rest normal (unit vector × 127)
    s16 texS, texT;         // texture coordinates (s10.5)
    u8 alpha;               // vertex alpha
} SSBBSkinVertex;           // 20 bytes

// Per-vertex bone weights (generated by converter, static)
typedef struct {
    u8 boneIndex[SSBB_MAX_INFLUENCES]; // bone indices into skeleton
    u8 weight[SSBB_MAX_INFLUENCES];    // weights 0-255, sum = 255
} SSBBSkinWeight;                      // 8 bytes

// Per-bone local position from COLLADA (float precision, matches inv_bind computation)
typedef struct {
    f32 x, y, z; // local position in DAE space (float, NOT truncated)
} SSBBSkinBonePos;

// Complete skinned mesh data (tag must match forward decl in ssbb_character.h)
typedef struct SSBBSkinMesh {
    u16 vertexCount;
    u16 boneCount;
    SSBBSkinVertex* vertices;       // [vertexCount] bind-pose vertex data
    SSBBSkinWeight* weights;        // [vertexCount] per-vertex bone weights
    MtxF* invBindMatrices;          // [boneCount] inverse bind matrices from COLLADA
    SSBBSkinBonePos* bonePositions; // [boneCount] float local positions (matches inv_bind)
    MtxF daeToF64;                  // DAE→F64 coordinate transform (auto-detected by converter)
    MtxF f64ToDae;                  // inverse(DaeToF64), pre-computed by converter
    Gfx* displayList;               // single DL, vertices via segment 0x08
    Gfx* materialDL;                // material DL (texture load + combiner), NULL = flat color
    // Brawl characters use three leading motion bones whose translation must be
    // discarded because Actor.world.pos owns movement.  Native/custom rigs can
    // opt out and keep their real root transform (Wolf Link uses this).
    u8 neutralizeRootMotion;
    // Secondary mesh (eyes, etc.) — drawn after main mesh with different material
    struct SSBBSkinMesh* secondaryMesh; // NULL = no secondary mesh
    // Runtime state (allocated at init, not generated)
    Vtx* vtxBuf[2]; // double-buffered Vtx arrays
    u8 bufIndex;    // current write buffer (0 or 1)
    // Blend each bone's TRS between the two frames around the fractional
    // curFrame instead of snapping to the integer one.  Off by default so the
    // Brawl rigs keep their exact per-frame poses; Wolf Link turns it on
    // because its 30 fps clips play at 1.5 frames per 20 Hz tick and would
    // stutter otherwise.  Only safe when consecutive frames have continuous
    // Euler angles (the wolf exporter guarantees that).
    u8 interpolateFrames;
} SSBBSkinMesh;

// Initialize skin mesh runtime buffers (allocate Vtx double buffers)
void SSBBSkin_Init(SSBBSkinMesh* skin);

// Free skin mesh runtime buffers
void SSBBSkin_Destroy(SSBBSkinMesh* skin);

// Full skinned draw: compute bone matrices, blend vertices, draw DL
void SSBBSkin_Draw(SSBBCharacterInstance* inst, PlayState* play, Vec3f* pos, Vec3s* rot);

// Model-space bone position from the last draw (see ssbb_skin.c)
s32 SSBBSkin_GetBoneWorldPos(s32 boneIndex, Vec3f* out);

#endif // SSBB_SKIN_H
