// Generated by build_epona_native_templates.py from the native OoT/MM display lists.
// A custom binary list may leave IsCustom=false. Verify its whole command layout
// before using fixed UV masks, especially texture-load sizes that the renderer trusts.
#pragma once

#include <libultraship/libultra/gbi.h>
#include <cstdint>
#include <string_view>
#include <vector>

namespace EponaCosmetics {
struct NativeCacheOperand {
    uint16_t index;
    uint32_t original;
};
inline constexpr NativeCacheOperand kNativeCacheOperands[] = {
    { 5, 0x00000000 },   { 31, 0x00000000 },  { 62, 0x00000000 },  { 87, 0x00000000 },  { 101, 0x00000000 },
    { 114, 0x00000000 }, { 150, 0x00000000 }, { 214, 0x00000000 }, { 230, 0x00000000 }, { 5, 0x00000000 },
    { 18, 0x00000000 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 5, 0x00000000 },   { 18, 0x00000000 },
    { 5, 0x00000000 },   { 18, 0x00000000 },  { 3, 0x00000000 },   { 18, 0x00000000 },  { 27, 0x00000000 },
    { 35, 0x000000D0 },  { 52, 0x00000000 },  { 60, 0x00000280 },  { 71, 0x00000000 },  { 79, 0x00000360 },
    { 89, 0x00000000 },  { 97, 0x00000470 },  { 117, 0x00000000 }, { 125, 0x000005C0 }, { 5, 0x00000000 },
    { 18, 0x00000000 },  { 23, 0x00000000 },  { 31, 0x00000050 },  { 5, 0x00000000 },   { 18, 0x00000000 },
    { 23, 0x00000000 },  { 31, 0x00000050 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 23, 0x00000000 },
    { 31, 0x00000050 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 23, 0x00000000 },  { 31, 0x00000050 },
    { 5, 0x00000000 },   { 18, 0x00000000 },  { 24, 0x00000000 },  { 33, 0x000000A0 },  { 40, 0x00000280 },
    { 44, 0x00000000 },  { 52, 0x000002E0 },  { 62, 0x000004C0 },  { 5, 0x00000000 },   { 28, 0x00000000 },
    { 101, 0x00000000 }, { 121, 0x00000000 }, { 183, 0x00000000 }, { 13, 0x00000000 },  { 25, 0x00000000 },
    { 35, 0x00000000 },  { 43, 0x000000E0 },  { 58, 0x00000000 },  { 66, 0x000001E0 },  { 74, 0x00000000 },
    { 82, 0x00000290 },  { 91, 0x00000000 },  { 99, 0x00000360 },  { 109, 0x00000000 }, { 117, 0x00000400 },
    { 5, 0x00000000 },   { 18, 0x00000000 },  { 27, 0x00000000 },  { 35, 0x000000B0 },  { 5, 0x00000000 },
    { 18, 0x00000000 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 27, 0x00000000 },  { 35, 0x000000B0 },
    { 5, 0x00000000 },   { 18, 0x00000000 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 27, 0x00000000 },
    { 35, 0x000000B0 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 5, 0x00000000 },   { 18, 0x00000000 },
    { 27, 0x00000000 },  { 35, 0x000000B0 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 13, 0x00000000 },
    { 25, 0x00000000 },  { 35, 0x00000000 },  { 43, 0x000000E0 },  { 58, 0x00000000 },  { 66, 0x000001E0 },
    { 74, 0x00000000 },  { 82, 0x00000290 },  { 91, 0x00000000 },  { 99, 0x00000360 },  { 109, 0x00000000 },
    { 117, 0x00000400 }, { 5, 0x00000000 },   { 18, 0x00000000 },  { 5, 0x00000000 },   { 18, 0x00000000 },
    { 27, 0x00000000 },  { 35, 0x000000B0 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 5, 0x00000000 },
    { 18, 0x00000000 },  { 27, 0x00000000 },  { 35, 0x000000B0 },  { 5, 0x00000000 },   { 18, 0x00000000 },
    { 27, 0x00000000 },  { 35, 0x000000B0 },  { 5, 0x00000000 },   { 18, 0x00000000 },  { 5, 0x00000000 },
    { 18, 0x00000000 },  { 27, 0x00000000 },  { 35, 0x000000B0 },  { 5, 0x00000000 },   { 18, 0x00000000 },
    { 5, 0x00000000 },   { 28, 0x00000000 },  { 101, 0x00000000 }, { 121, 0x00000000 }, { 183, 0x00000000 },
    { 5, 0x00000000 },   { 28, 0x00000000 },  { 101, 0x00000000 }, { 121, 0x00000000 }, { 183, 0x00000000 },
};
struct NativeTemplate {
    std::string_view path;
    uint64_t fingerprint;
    size_t commands;
    bool mm;
    size_t cacheFirst;
    size_t cacheCount;
};
inline constexpr NativeTemplate kNativeTemplates[] = {
    { "objects/object_horse/gEponaBodyLimbSkinLimbDL_00B7C0", 0x44F8AF795879FED1ULL, 245, false, 0, 9 },
    { "objects/object_horse/gEponaCannon1LimbDL_000BB0", 0x84DCA464F30B21E2ULL, 26, false, 9, 2 },
    { "objects/object_horse/gEponaCannon2LimbDL_000FA0", 0x14726472EB7C9904ULL, 26, false, 11, 2 },
    { "objects/object_horse/gEponaCannon3LimbDL_001370", 0x0B1DBE16BE8A577CULL, 26, false, 13, 2 },
    { "objects/object_horse/gEponaCannon4LimbDL_001740", 0xD9DB5E4B0B3B5CD7ULL, 26, false, 15, 2 },
    { "objects/object_horse/gEponaHeadLimbDL_00AC20", 0x7D602DFC000A14D6ULL, 134, false, 17, 12 },
    { "objects/object_horse/gEponaHoof1LimbDL_0009B0", 0x597AE3328B6179F3ULL, 40, false, 29, 4 },
    { "objects/object_horse/gEponaHoof2LimbDL_000DA0", 0xF247C5F8D80EB417ULL, 40, false, 33, 4 },
    { "objects/object_horse/gEponaHoof3LimbDL_001170", 0x8C73FA19558E3D00ULL, 40, false, 37, 4 },
    { "objects/object_horse/gEponaHoof4LimbDL_001540", 0x28F04E687B3853FCULL, 40, false, 41, 4 },
    { "objects/object_horse/gEponaSaddleLimbDL_00B5E0", 0xB3B6348FBF6D7DFCULL, 70, false, 45, 8 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_0077D8SkinLimbDL_007B30", 0x84B422F1A449DCF1ULL, 197,
      false, 53, 5 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_007858DL_000C70", 0x51315D7BD5AE0D4EULL, 134, false, 58,
      12 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_0078C8DL_001298", 0xA6F3BB583126DABCULL, 40, false, 70,
      4 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_0078D8DL_0011E8", 0xE35E301FF5B17B06ULL, 26, false, 74,
      2 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_007948DL_0013A8", 0xD560F19F61D1A059ULL, 40, false, 76,
      4 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_007958DL_0014B8", 0xCDE0CA5762DD4DCAULL, 26, false, 80,
      2 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_0079C8DL_0010D8", 0x66E2B9504ABBCD49ULL, 40, false, 82,
      4 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_0079D8DL_001028", 0xF6C3E2DAF72A23A5ULL, 26, false, 86,
      2 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_007A48DL_001568", 0x852C5C9E1EFA8485ULL, 40, false, 88,
      4 },
    { "objects/object_horse_link_child/gChildEponaSkelLimbsLimb_007A58DL_001678", 0xEBEE01F6C0BF7855ULL, 26, false, 92,
      2 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_000C70", 0x0310709EE74EFD62ULL, 134, true, 94, 12 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_001028", 0xB636122917EB243DULL, 26, true, 106, 2 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_0010D8", 0x5E69EFDE15A49DC4ULL, 40, true, 108, 4 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_0011E8", 0xDA5461E054539609ULL, 26, true, 112, 2 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_001298", 0x7F20D2AE632A94C6ULL, 40, true, 114, 4 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_0013A8", 0x691BFA25D6DFF6A1ULL, 40, true, 118, 4 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_0014B8", 0xB58910532073F2ECULL, 26, true, 122, 2 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_001568", 0xB0A320440343718BULL, 40, true, 124, 4 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_001678", 0x58385AA491331D3DULL, 26, true, 128, 2 },
    { "objects/object_horse_link_child/object_horse_link_child_DL_00D500", 0x2A97F7581873DA21ULL, 197, true, 130, 5 },
    { "objects/object_horse_link_child/object_horse_link_child_Skinlimb_00A138SkinLimbDL_00D500", 0x2A97F7581873DA21ULL,
      197, true, 135, 5 },
};

inline bool NativeTemplateMatches(std::string_view path, const std::vector<Gfx>& commands, bool mm) {
    if (path.starts_with("__OTR__")) {
        path.remove_prefix(7);
    }
    for (const auto& expected : kNativeTemplates) {
        if (expected.path != path || expected.mm != mm || expected.commands != commands.size()) {
            continue;
        }
        uint64_t fingerprint = 14695981039346656037ULL;
        size_t cacheIndex = expected.cacheFirst;
        for (size_t index = 0; index < commands.size(); ++index) {
            const auto& command = commands[index];
            uintptr_t operand = command.words.w1;
            if (cacheIndex < expected.cacheFirst + expected.cacheCount &&
                kNativeCacheOperands[cacheIndex].index == index) {
                // Fast3D replaces these exact SETTIMG_HASH/VTX_HASH operands with host pointers.
                // Normalize only a cached pointer; a changed native offset must still be rejected.
                if (operand > 0xFFFFF) {
                    operand = kNativeCacheOperands[cacheIndex].original;
                }
                ++cacheIndex;
            }
            for (const auto word : { command.words.w0, operand }) {
                if (static_cast<uint64_t>(word) > UINT32_MAX) {
                    return false;
                }
                for (unsigned shift = 0; shift < 32; shift += 8) {
                    fingerprint = (fingerprint ^ ((word >> shift) & 0xFF)) * 1099511628211ULL;
                }
            }
        }
        return fingerprint == expected.fingerprint;
    }
    return false;
}
} // namespace EponaCosmetics
