// Generated by scripts/diagnostics/build_epona_masks.py from inspected native OoT/MM materials.
// Immutable UV masks only. Each engine owns its own display-list/texture/cache state.
#ifndef COMBO_EPONA_COSMETIC_MASKS_H
#define COMBO_EPONA_COSMETIC_MASKS_H

#include <array>
#include <cstdint>
#include <string_view>
#include <vector>

namespace EponaMasks {
enum class Part { Coat, WhiteHair, Eyes };

struct Mask {
    uint8_t width;
    uint8_t height;
    std::array<uint32_t, 32> selected;
};

// clang-format off
inline constexpr Mask kMasks[] = {
    { 16, 16, { 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu } },
    { 8, 8, { 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FFu } },
    { 16, 8, { 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu } },
    { 16, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000004u, 0x000003DFu, 0x0000FBDFu, 0x0000FFFFu } },
    { 16, 16, { 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000D87Fu, 0x0000FF7Fu, 0x0000FD2Au, 0x0000F420u, 0x00004420u, 0x00000000u } },
    { 16, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000008u, 0x0000E31Du, 0x00008A0Du, 0x00000606u, 0x00000400u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u } },
    { 16, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00002081u, 0x0000F1F3u, 0x0000D7F7u, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu } },
    { 8, 32, { 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x00000007u, 0x00000007u, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x00000007u, 0x00000007u, 0x0000000Fu, 0x0000001Fu, 0x0000001Fu, 0x0000001Fu, 0x0000001Fu, 0x0000003Fu, 0x0000007Fu, 0x0000007Fu, 0x0000007Fu, 0x000000FFu, 0x0000007Fu, 0x0000007Fu, 0x0000007Fu, 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FFu } },
    { 16, 32, { 0x0000F800u, 0x0000F800u, 0x0000F800u, 0x0000FB80u, 0x0000FFC0u, 0x0000FFC0u, 0x0000FE00u, 0x0000FC00u, 0x0000FC00u, 0x0000F800u, 0x0000F800u, 0x0000F800u, 0x0000F800u, 0x0000F800u, 0x0000F800u, 0x0000F800u, 0x0000FC00u, 0x0000F800u, 0x0000FC00u, 0x0000FC00u, 0x0000F800u, 0x0000F000u, 0x0000F000u, 0x0000C000u, 0x0000C000u, 0x0000C000u, 0x0000C000u, 0x00008000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u } },
    { 32, 16, { 0xFFFC0000u, 0xFFFC0000u, 0xFFFC0000u, 0xFFFC0000u, 0xFFE00000u, 0xFFC00000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xFFC00000u, 0xFFE00000u, 0xFFFC0000u, 0xFFFC0000u, 0xFFFC0000u, 0xFFFC0000u } },
    { 32, 16, { 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFC0FFu, 0xFFC0001Fu, 0xFFC00007u, 0xFFC00007u, 0xFFE00003u, 0xFFF00001u, 0xFFFC000Fu, 0xFFFF001Fu, 0xFFFFE03Fu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu } },
    { 32, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x0000FC00u, 0x0001CE20u, 0x00018638u, 0x0001CE78u, 0x0000F870u, 0x000001E0u, 0x00003FC0u, 0x00001E00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u } },
    { 32, 16, { 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFC03FFFu, 0xFFE0003Fu, 0xFFF00001u, 0xFFFC000Fu, 0xFFFF001Fu, 0xFFFFE03Fu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu } },
    { 32, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x0000F800u, 0x000001E0u, 0x00003FC0u, 0x00001E00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u } },
    { 32, 16, { 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFBFFFFFu, 0xFF9FFFFFu, 0xFFC3FFFFu, 0xFFF07FF3u, 0xFFF80007u, 0xFFFE0007u, 0xFFFFE01Fu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu } },
    { 16, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000008u, 0x0000E31Du, 0x00008A0Du, 0x00000606u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u } },
    { 16, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00002081u, 0x0000E0F3u, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu } },
    { 16, 16, { 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000010u, 0x00008010u, 0x0000C536u, 0x0000EFBFu, 0x0000FFFFu } },
    { 16, 16, { 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFFFu, 0x0000FFEFu, 0x00007FEFu, 0x00007EEBu, 0x00003040u, 0x00000000u } },
    { 4, 4, { 0x0000000Fu, 0x0000000Fu, 0x0000000Fu, 0x0000000Fu } },
    { 8, 32, { 0x000000F0u, 0x000000F0u, 0x000000F0u, 0x000000E0u, 0x000000E0u, 0x000000E0u, 0x000000C0u, 0x000000C0u, 0x000000C0u, 0x000000C0u, 0x000000E0u, 0x000000E0u, 0x000000C0u, 0x000000C0u, 0x000000E0u, 0x000000E0u, 0x000000F0u, 0x000000F0u, 0x000000F8u, 0x000000F8u, 0x000000F8u, 0x000000FCu, 0x000000FEu, 0x000000FFu, 0x000000FFu, 0x000000FFu, 0x000000FEu, 0x000000FEu, 0x000000FEu, 0x000000FFu, 0x000000FFu, 0x000000FFu } },
    { 16, 16, { 0x0000FFC0u, 0x0000FFC0u, 0x0000FFC0u, 0x0000FFC0u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF80u, 0x0000FF00u, 0x0000FE00u, 0x0000FC00u } },
    { 32, 32, { 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu, 0xFFFFFFFFu } },
};

struct Entry {
    std::string_view name;
    std::array<const Mask*, 3> parts;
};

inline constexpr Entry kEntries[] = {
    { "gEponaChestTex", { &kMasks[0], nullptr, nullptr } },
    { "gEponaNeckTex", { &kMasks[0], nullptr, nullptr } },
    { "gEponaShoulderTex", { &kMasks[0], nullptr, nullptr } },
    { "gEponaThighTex", { &kMasks[0], nullptr, nullptr } },
    { "gEponaHairTex", { &kMasks[1], nullptr, nullptr } },
    { "gEponaCrestTex", { nullptr, &kMasks[2], nullptr } },
    { "gEponaManeTex", { &kMasks[3], &kMasks[4], nullptr } },
    { "gEponaFeatheringTex", { &kMasks[5], &kMasks[6], nullptr } },
    { "gEponaForeheadTex", { &kMasks[7], nullptr, nullptr } },
    { "gEponaNostrilsTex", { &kMasks[8], nullptr, nullptr } },
    { "gEponaSaddleGirthTex", { &kMasks[9], nullptr, nullptr } },
    { "gEponaEyeOpenTex", { &kMasks[10], nullptr, &kMasks[11] } },
    { "gEponaEyeHalfTex", { &kMasks[12], nullptr, &kMasks[13] } },
    { "gEponaEyeClosedTex", { &kMasks[14], nullptr, nullptr } },
    { "object_horse_link_childTex_001F68", { &kMasks[15], &kMasks[16], nullptr } },
    { "object_horse_link_child_Tex_001F68", { &kMasks[15], &kMasks[16], nullptr } },
    { "object_horse_link_childTex_002168", { &kMasks[17], &kMasks[18], nullptr } },
    { "object_horse_link_child_Tex_002168", { &kMasks[17], &kMasks[18], nullptr } },
    { "object_horse_link_childTex_002368", { nullptr, &kMasks[0], nullptr } },
    { "object_horse_link_child_Tex_002368", { nullptr, &kMasks[0], nullptr } },
    { "object_horse_link_childTex_002568", { &kMasks[19], nullptr, nullptr } },
    { "object_horse_link_child_Tex_002568", { &kMasks[19], nullptr, nullptr } },
    { "object_horse_link_childTex_002588", { &kMasks[20], nullptr, nullptr } },
    { "object_horse_link_child_Tex_002588", { &kMasks[20], nullptr, nullptr } },
    { "object_horse_link_childTex_002788", { &kMasks[21], nullptr, nullptr } },
    { "object_horse_link_child_Tex_002788", { &kMasks[21], nullptr, nullptr } },
    { "object_horse_link_childTex_008120", { &kMasks[0], nullptr, nullptr } },
    { "object_horse_link_child_Tex_00DAF0", { &kMasks[0], nullptr, nullptr } },
    { "object_horse_link_childTex_008320", { &kMasks[22], nullptr, nullptr } },
    { "object_horse_link_child_Tex_00DCF0", { &kMasks[22], nullptr, nullptr } },
    { "gChildEponaEyeOpenTex", { &kMasks[10], nullptr, &kMasks[11] } },
    { "gChildEponaEyeHalfTex", { &kMasks[12], nullptr, &kMasks[13] } },
    { "gChildEponaEyeCloseTex", { &kMasks[14], nullptr, nullptr } },
};

// clang-format on
inline const Mask* FindMask(std::string_view textureName, Part part) {
    textureName.remove_prefix(
        textureName.find_last_of('/') == std::string_view::npos ? 0 : textureName.find_last_of('/') + 1);
    for (const auto& entry : kEntries) {
        if (entry.name == textureName) {
            return entry.parts[static_cast<size_t>(part)];
        }
    }
    return nullptr;
}

// The renderer removes pixels whose mask byte is nonzero. Expand once when a
// display-list copy is cached; rainbow updates only change GPU color commands.
inline std::vector<uint8_t> BuildInverseMask(std::string_view textureName, Part part) {
    const auto* mask = FindMask(textureName, part);
    if (mask == nullptr) {
        return {};
    }
    std::vector<uint8_t> pixels(mask->width * mask->height);
    for (size_t y = 0; y < mask->height; ++y) {
        for (size_t x = 0; x < mask->width; ++x) {
            pixels[y * mask->width + x] = (mask->selected[y] & (uint32_t{ 1 } << x)) == 0;
        }
    }
    return pixels;
}
} // namespace EponaMasks

#endif
